### ISSUE TITLE
ES6 syntax exposed in lib/

### ISSUE THREAD

**Issue by butchler** [ottypes/text#9]
As of version 1.02, code that uses ES6 syntax is exposed in the `lib/` folder. This is problematic for people who want to use this library but need their code to run on older browsers that don't support ES6 syntax natively, such as IE11.

Note: Even when using a bundler such as Webpack/Parcel/Rollup, the default configuration for most bundlers is to not attempt to transpile any of the dependencies, assuming that they are already transpiled to ES5 or older. See https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features for more background.

**Comment by josephg** [comment]
ES6 is about 4 years old now and IE11 is (thankfully) down to 2% worldwide usage. If IE11 support is important to you, I’m going to leave transpiling to you.

Sorry for the hassle, but I choose not to volunteer my time and attention fixing legacy IE bugs.

**Comment by butchler** [comment]
Fair enough. Mind if I make a PR updating the README to warn people to use 1.0.1 or transpile themselves if they need support for older browsers?

**Comment by butchler** [comment]
That said, this doesn't necessarily just affect IE, but older browser that doesn't support ES6 syntax. Newer syntax such as `async`/`await` will also be less widely supported, so when making changes in the future you may need to be careful to make sure you're not using any syntax that's too new and won't work on more than 2% of browsers. It may be easier to just set up a transpiler yourself and then you don't have to think about those things.

**Comment by josephg** [comment]
Yeahhh I don’t like the idea of transpiling everything back to ES5. There have been a lot of features added into JavaScript that I like, and not all of them can be polyfilled efficiently. For example, `Set` loses its performance advantages when polyfilled and `WeakSet` / `WeakMap` don’t work as intended at all. Anything using async await grows by ~50% or so, and I suspect the polyfilled version is far less efficient to boot. Transpiling back to es5 isn’t fire and forget. It’s fire and pay the cost in every browser and every platform.

As for other platforms, you can see the runtime support here: https://kangax.github.io/compat-table/es6/ . IE11 is the only browser that is still used that has issues. Also you can see that Babel (and other polyfilled) have only partial support for many features. 

But sure - go ahead and add a warning to the readme if you like. Link this issue.

**Comment by butchler** [comment]
100% agree about the cost of transpiling to ES5, but I would recommend using the `package.esnext` field for this instead of shipping something broken in the `module` field. See http://2ality.com/2017/06/pkg-esnext.html. I really hope the `esnext` field gains more popularity and starts getting provided by more npm packages.

**Comment by josephg** [comment]
Hm. It would be nice if modules explicitly specified which version of ES they exposed - then a bundling tool like parcel could check for ES6 modules and transpile those, while leaving everything else alone.

But as for "shipping something broken", I don't think there's any standard saying that `main` in a package.json file needs to point to ES5 code. Why es5? While we're at it why not es3? What about all those packages that "ship something broken" because their code doesn't work properly in IE5 or netscape 4?

Its not perfect, but as far as I know the standard is to either explicitly specify an `engines` field in package.json to specify which node versions are supported, or to just maintain compatibility with HEAD + all current [LTS releases of node](https://github.com/nodejs/Release). Right now thats node 8 onwards. Node 8 [supports ES6](http://kangax.github.io/compat-table/es2016plus/) (aka ES2015). And it also supports ES2016 and ES2017, just like Edge and Firefox.

The fact that node packages (in node package manager) can often be packaged to run in browsers is a happy and useful coincidence. But no explicit guarantee is made that this npm module (or any other) will constrain itself to using a 4 year old javascript feature set simply to maintain support for IE. I'm happy to fix IE11-specific bugs, but again, I'm not going to waste my weekends adding and supporting a transpiler. What version should that transpiler target, anyway? Any answer is going to be a bit wrong for someone. Its a much better use of time if *you* make that decision for your application, and transpile all your dependancies in one swoop to match your desired browser support. Then when IE11 reaches end-of-life ([Jan 2020?](https://en.wikipedia.org/wiki/Internet_Explorer_11)) one configuration change in your build process will allow your entire application to stop paying the ES5 performance cost.

**Comment by butchler** [comment]
> Hm. It would be nice if modules explicitly specified which version of ES they exposed - then a bundling tool like parcel could check for ES6 modules and transpile those, while leaving everything else alone.

Yeah, this would be really nice. I guess it's hard to do well since the standards and tools are constantly evolving?

> But as for "shipping something broken"

Sorry, I was speaking under the assumption that this package was designed to be suitable for running in the browser. In that case, I would consider not supporting all browsers by default to be broken, unless you have a really strong reason not to.

But if this was never really designed with the browser in mind, then you're absolutely right: it's just a happy coincidence that it happened to work in IE before, and I don't think anything needs to be changed about this package.

To be honest, I've only been looking at things from a browser-centric viewpoint that I almost completely forgot that NPM was originally designed for Node, and the fact that it started being used for dependencies in the browser is somewhat of a hack. =P

That said... Providing a version of the code specifically intended for running in the browser is exactly what the `browser` field in `package.json` is for. XD I don't think you should spend any effort on this, but if I have some time I might make a PR for adding a `browser` field.

**Comment by josephg** [comment]
> I guess it's hard to do well since the standards and tools are constantly evolving?

Hard because the tools *aren't* evolving at the pace they were a few years ago. But to do it you'd just need to get consensus amongst developers that this is a good idea. Specifically the bundler authors. If parcel / webpack started looking for a tag like that it would happen. The `browser` field in package.json happened because browserify started looking for it and everyone else followed suit.

Anyway, I appreciate the offer but this package runs fine in all the browsers that 98% of the world's population use. It just doesn't work properly in IE<=11. If you have requirements like this, configure your bundler. Its a 1 line change. I don't want to bear that complexity cost here, and I don't want other browsers to pay for IE11's inadequacies.

**Comment by DC-jc** [comment]
I know this is an old issue and isn't likely to receive much attention, but I still like to comment that moving from ES5 to ES6 isn't really a problem, as long as it's recognized as a breaking change and versioned accordingly. I'm currently Dockerizing a legazy app (actively used but not maintained) and having sub-dependencies that relies on version "^1.0.1" which pulls down version 1.0.2 and then breaks at runtime.

**Comment by josephg** [comment]
Good point. This was probably a mistake in retrospect.
